// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEBoRfeK5sTLGhaMx4-5saFfAmNqbMbcM',
    appId: '1:944876086636:web:8347bc69829fdec634ff49',
    messagingSenderId: '944876086636',
    projectId: 'laundry-75781',
    authDomain: 'laundry-75781.firebaseapp.com',
    databaseURL: 'https://laundry-75781-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-75781.appspot.com',
    measurementId: 'G-5N9JETB8SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByWNDwew9jeX8_l8UC62KsNVxREpxsZz4',
    appId: '1:944876086636:android:59b3e0c2b25c929634ff49',
    messagingSenderId: '944876086636',
    projectId: 'laundry-75781',
    databaseURL: 'https://laundry-75781-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-75781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNMsE7bDbGKLDMuS6NVhokoY0HdtSVtg',
    appId: '1:944876086636:ios:9e90c293f874154734ff49',
    messagingSenderId: '944876086636',
    projectId: 'laundry-75781',
    databaseURL: 'https://laundry-75781-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-75781.appspot.com',
    iosClientId: '944876086636-vtv14s3m4752act4cnnv47jf9qgh54q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNMsE7bDbGKLDMuS6NVhokoY0HdtSVtg',
    appId: '1:944876086636:ios:9e90c293f874154734ff49',
    messagingSenderId: '944876086636',
    projectId: 'laundry-75781',
    databaseURL: 'https://laundry-75781-default-rtdb.firebaseio.com',
    storageBucket: 'laundry-75781.appspot.com',
    iosClientId: '944876086636-vtv14s3m4752act4cnnv47jf9qgh54q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundry',
  );
}
